export let msjAreaCSH= 'Ciencias Sociales y Humanística'
export let carrerasAreaCSH= ' • Psicología, • Trabajo Social, • Idiomas, • Educación Internacional, • Historia y Geografía, • Periodismo, • Periodismo Digital, • Derecho, • Ciencias Políticas, • Sociología, • Antropología, • Arqueología, • Gestión Social y Desarrollo, • Consejería Familiar, • Comunicación y Publicidad, • Administración Educativa, • Educación Especial, • Psicopedagogía, • Estimulación Temprana, • Traducción Simultánea, • Lingüística, • Educación de Párvulos, • Bibliotecología, • Museología, • Relaciones Internacionales y Diplomacia, • Comunicación Social con énfasis en márquetin y gestión de empresas, • Redacción Creativa y Publicitaria, • Relaciones públicas y comunicación organizacional, • Hotelería y turismo, • Teología, • Institución sacerdotal.'

export let msjAreaEAF= 'Económica, Administrativa y Financiera'
export let carrerasAreaEAF= ' • Administración de empresas, • Contabilidad, • Auditoría, • Ventas, • Márquetin estratégico, • Gestión y negocios internacionales, • Gestión empresarial, • Gestión financiera, • Ingeniería comercial, • Comercio exterior, • Banca y finanzas, • Gestión de recursos humanos,• Comunicaciones integradas en márquetin, • Administración de empresas ecoturísticas y de hospitalidad, • Ciencias económicas y financieras, • Administración y ciencias políticas, • Ciencias empresariales, • Comercio electrónico, • Emprendimiento, • Gestión de organismos públicos (municipios, ministerios, etc.), • Gestión de centros educativos.'

export let msjAreaCT= 'Ciencia y Tecnología'
export let carrerasAreaCT= ' • Ingeniería en sistemas computacionales, • Geología, • Ingeniería civil, • Arquitectura, • Electrónica, • Telemática, • Telecomunicaciones, • Ingeniería mecatrónica (robótica), • Imagen y sonido, • Minas, • Petróleo y metalurgia, • Ingeniería mecánica, • Ingeniería industrial, • Física, • Matemáticas aplicadas, • Ingeniería en estadística, • Ingeniería automotriz, • Biotecnología ambiental, • Ingeniería geográfica, • Carreras militares (marina, aviación, ejército), • Ingeniería en costas y obras portuarias, • Estadística informática, • Programación y desarrollo de sistemas, • Tecnología en informática educativa, • Astronomía, • Ingeniería en ciencias geográficas y desarrollo sustentable.'

export let msjAreaAC= 'Arte y Creatividad'
export let carrerasAreaAC= ' • Diseño gráfico, • Diseño y decoración de interiores, • Diseño de jardines, • Diseño de modas, • Diseño de joyas, • Artes plásticas (pintura, escultura, danza, teatro, artesanía, cerámica), • Dibujo publicitario, • Eestauración y museología, • Modelaje, • Fotografía, • Gestión gráfica y publicitaria, • Locución y publicidad, • Actuación, • Camarografía, • Arte industrial, • Producción audiovisual y multimedia, • Comunicación y producción en radio y televisión, • Diseño del paisaje, cine y video, • Comunicación escénica para televisión, • Música.'

export let msjAreaCB= 'Ciencias Ecológicas, Biológicas y de la Salud'
export let carrerasAreaCB= ' • Biología, • Bioquímica, • Farmacia, • Biología marina, • Bioanálisis, • Biotecnología, • Ciencias ambientales, • Zootecnia, • Veterinaria, • Nutrición y estética, • Cosmetología, • Dietética y estética, • Medicina, • Obstetricia, • Urgencias médicas, • Odontología, • Enfermería, • Tecnología, • Eceanografía y ciencias ambientales, • Agronomía, • Horticultura y fruticultura, • Ingeniería de alimentos, • Gastronomía, • Cultura física, • Deportes y rehabilitación, • Gestión ambiental, • Ingeniería ambiental, • Optometría, • Homeopatía, • Reflexología.'